[package]

name = "alsa-sys"
version = "0.0.6"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
build = "build.rs"
description = "Bindings for the ALSA project (Advanced Linux Sound Architecture)"
license = "MIT"

[dependencies]
libc = "*"

[build-dependencies]
pkg-config = "0.3"
